-- PREGUNTA 1
CREATE TABLE COM_CLIENTES(
    CLIENTE_ID NUMBER PRIMARY KEY,
    RAZON_SOCIAL VARCHAR2(150) NOT NULL,
    RUC VARCHAR2(11) NOT NULL,
    DIRECION VARCHAR2(200) NOT NULL,
    TELEFONO VARCHAR2(20),
    CORREO VARCHAR2(100),
    EJECUTIVO_ID NUMBER NOT NULL,
    ACTIVO NUMBER NOT NULL,
    USUARIO_CREACION VARCHAR2(50) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    USUARIO_ACTUALIZACION VARCHAR2(50)
);

-- PREGUNTA 2
COMMENT ON COLUMN COM_CLIENTES.CLIENTE_ID IS 'IDENTIFICADOR UNICO DEL CLIENTE MAYORISTA';
COMMENT ON COLUMN COM_CLIENTES.RAZON_SOCIAL IS 'RAZON SOCIAL O NOMBRE COMERCIAL DEL CLIENTE';
